# Generated by Django 5.1.4 on 2025-04-04 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 4, 19, 9, 40, 345323, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
