# Generated by Django 5.1.4 on 2025-04-04 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 4, 19, 23, 44, 140897, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
