# Generated by Django 5.1.4 on 2025-04-13 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customuser_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 13, 16, 51, 59, 24713), null=True),
        ),
    ]
