# Generated by Django 5.0.1 on 2025-04-13 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customuser_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 13, 20, 12, 7, 263087), null=True),
        ),
    ]
